### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [JasonCromer/CSHelper#1]
Does this software have a license?

**Comment by JasonCromer** [comment]
Yes it does. There should be a license in the root directory of this project called license.txt.
Are you looking to modify/use this source code?

**Comment by JasonCromer** [comment]
License is available for user, thus this issue is closed.

**Comment by ghost** [comment]
Yes, thank you.

**Comment by JasonCromer** [comment]
What are you wanting to use it for?

**Comment by ghost** [comment]
Distribution on [F-Droid](https://f-droid.org), an alternative app platform for FOSS android.

**Comment by ghost** [comment]
Can we assume this is GPLv2+ ("GPLv2 and later")? Because you are using Android support libraries, which are Apache2 licensed. Apache2 and GPLv2 are incompatible, while GPLv2+/3/3+ should be okay.

**Comment by JasonCromer** [comment]
What are you wishing to use this for? Also, what parts of the application do you wish to use?

**Comment by JasonCromer** [comment]
@twzkxkan, since I do not have direct control of how my application is being used in FOSS, I do not want it distributed on there.

**Comment by pserwylo** [comment]
@JasonCromer: Sorry to hear that you do not want your app on F-Droid. Before dropping the issue, I'd just clarify that if your app _was_ to be released on F-Droid, it is still credited to you, with a link to the original source code in this repository. F-Droid does not try to claim apps as their own, but it does build open source licensed software itself before distributing, so as to be sure what code is being compiled. This is apposed to taking binaries from the web and distributing them to users. Hope that helps clarify. Cheers.

**Comment by ghost** [comment]
@JasonCromer: That is a more general information for you. For further information about this licensing issue, see https://www.apache.org/licenses/GPL-compatibility.html and https://www.gnu.org/licenses/license-list.html#apache2

**Comment by JasonCromer** [comment]
@pserwylo, @krt16s, I appreciate the information you've both provided me, however it does not change my stance on having my app on F-Droid. This might change in the near future, but as of now, while I am still releasing updates to them on a regular basis, I do not want them available on F-Droid.
When I do decide otherwise, I'll re-open this issue and notify everyone on this thread.
